name: quick-release Github Action
description: Github Action to perform simple, and quick releases.
branding:
  icon: archive
  color: green
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  github-username:
    description: Set the Github username to use for creating/pushing updates.
    required: true
    default: ${{ github.actor }}
  git-user-name:
    description: Set the git users full name to use when release-it commits.
    required: true
    default: quick-release bump
  git-user-email:
    description: Set the git email address to use when release-it commits.
    required: false
  auto-resolve-command:
    description: Shell command to execute if a conflict occurs.
    required: false

outputs:
  version:
    description: version
  latestVersion:
    description: latestVersion returned from release-it
  changelog:
    description: changelog returned from release-it
runs:
  using: 'node12'
  main: dist/index.js
